### ISSUE TITLE
Balances list empty

### ISSUE THREAD

**Issue by rwiddhic96** [ipmach/USIcoins#5]
Even after creating two new users, balances list in Ganache is empty, does not show balances of users. Issue somewhere in users_op or users_data.sol )
<img width="539" alt="Screenshot 2020-12-12 at 15 51 26" src="https://user-images.githubusercontent.com/22234321/101987050-057e7f00-3c92-11eb-8c33-762b98401dcc.png">

**Comment by ipmach** [comment]
false alarm
